version: "3.8"

services:
  # Create client container
  client: # Name of our service
    build: ./client # path to dockerfile
    stdin_open: true
    tty: true
    ports: # Port binding to host from docker container
      - "3001:3000" # Bind port 3000 of host to 3000 of container
    container_name: client-docker
    restart: always # What to do if container crashes
    networks:
      - chat
    links:
      - api

  # Create api container
  api:
    build: ./api
    ports:
      - "8080:4000"
    container_name: api-docker
    restart: always
    command: npx sequelize db:migrate:undo:all
    command: npx sequelize db:migrate
    networks:
      - chat
    links:
      - db

  # Create database container
  db:
    image: mysql:5.7
    container_name: db-docker
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE}
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=${USER}
      # You can use whatever password you like
      - MYSQL_PASSWORD=${PASSWORD}
      # Password for root access
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - ./docker/data/db:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - chat

networks:
  chat:
