version: "3.8"

services:
  # Create client container
  client:
    build: ./client
    stdin_open: true
    tty: true
    ports: # Port binding to host from docker container
      - "3001:3000" # Bind port 3001 of host to 3000 of container
    container_name: client-docker
    restart: always # What to do if container crashes
    links:
      - api
    volumes: # For webpack dev server to use our local files:
      - ./client:/hermes/chat/client
      # see https://github.com/sass/node-sass/issues/2165 cuz node-sass
      - /hermes/chat/client/node_modules/
  # Create api container
  api:
    build: ./api
    ports:
      - "8080:4000"
    container_name: api-docker
    restart: always
    volumes: # For webpack dev server to use our local files
      - ./api:/hermes/chat/api
    links:
      - db
  # Create db container
  db:
    image: mysql:5.7
    container_name: db-docker
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    expose:
      - "3306"
      # Where datas will be persisted
    volumes:
      - ./docker/data/db:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
