export const campusList = [
    { name: "Amsterdam", value: "Amsterdam" },
    { name: "Barcelone", value: "Barcelone" },
    { name: "Berlin", value: "Berlin" },
    { name: "Biarritz", value: "Biarritz" },
    { name: "Bordeaux", value: "Bordeaux" },
    { name: "Bruxelles", value: "Bruxelles" },
    { name: "Bucarest", value: "Bucarest" },
    { name: "La Loupe ", value: "La Loupe " },
    { name: "Lille", value: "Lille" },
    { name: "Lisbonne", value: "Lisbonne" },
    { name: "Londres", value: "Londres" },
    { name: "Lyon", value: "Lyon" },
    { name: "Madrid", value: "Madrid" },
    { name: "Marseille", value: "Marseille" },
    { name: "Nantes", value: "Nantes" },
    { name: "Orléans", value: "Orléans" },
    { name: "Paris", value: "Paris" },
    { name: "Reims", value: "Reims" },
    { name: "Remote-FR", value: "Remote-FR" },
    { name: "Remote-EN", value: "Remote-EN" },
    { name: "Saintes", value: "Saintes" },
    { name: "Strasbourg", value: "Strasbourg" },
    { name: "Toulouse", value: "Toulouse" },
    { name: "Tours", value: "Tours" },
]